minimumReleaseAgeExcludePrune: true
trustPolicy: no-downgrade
shellEmulator: true

allowBuilds:
  esbuild: true

catalog:
  '@antfu/eslint-config': ^9.5.1
  '@clack/prompts': ^0.11.0
  '@types/archiver': ^8.0.0
  '@types/node': ^24.9.2
  archiver: ^8.0.0
  c12: ^3.3.0
  changelogen: ^0.6.2
  consola: ^3.4.2
  eslint: ^10.10.0
  eslint-plugin-format: ^2.0.1
  execa: ^10.0.1
  prettier: ^3.9.8
  publint: ^0.3.24
  scule: ^1.3.0
  tsdown: ^0.23.0
  typescript: ^5.9.3
  unplugin: ^3.4.0
  valibot: ^1.1.0
  vitest: ^5.0.1
