import type { EnvPrefix } from '../runtime/public-env.js'
import type { EnvField, EnvSchema } from '../types.js'
import { randomUUID } from 'node:crypto'
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { ensureMatrixEnvPrefix, publicConfigFields, publicEnvKeys } from '../runtime/public-env.js'

export interface GenerateMatrixTypesOptions {
  cwd: string
  env: Record<string, unknown>
  envPrefix?: EnvPrefix
  envSchema?: EnvSchema
  scope?: string
  output?: string
}

export function matrixRuntimeModuleId(scope?: string): string {
  if (!scope)
    return 'virtual:matrix/runtime'
  if (!/^[\w-]+$/.test(scope))
    throw new Error(`Invalid Matrix scope: ${scope}`)
  return `virtual:matrix/runtime/${scope}`
}

export function matrixTypeOutput(options: Pick<GenerateMatrixTypesOptions, 'cwd' | 'scope' | 'output'>): string {
  matrixRuntimeModuleId(options.scope)
  return path.resolve(options.cwd, options.output ?? (options.scope
    ? `.matrix/types/matrix-runtime-${options.scope}.d.ts`
    : '.matrix/types/matrix-runtime.d.ts'))
}

/** Render first so preparation can validate every scope before writing declarations. */
export function renderMatrixTypes(options: GenerateMatrixTypesOptions): string {
  const prefixes = ensureMatrixEnvPrefix(options.envPrefix)
  const schema = options.envSchema ?? {}
  const keys = publicEnvKeys({ ...schema, ...options.env }, prefixes)
  const fields = publicConfigFields(keys, prefixes, schema)
  const configNames = [...fields.keys()].filter(Boolean).sort()
  const field = (key: string): EnvField | undefined => Object.hasOwn(schema, key) ? schema[key] : undefined
  const optional = (key: string): string => field(key)?.optional && field(key)?.default === undefined ? '?' : ''
  const configType = (key: string): string => {
    const declaration = field(key)
    return declaration?.type === 'enum'
      ? [...new Set(declaration.values)].map(value => JSON.stringify(value)).join(' | ')
      : declaration?.type ?? 'string'
  }
  const moduleId = matrixRuntimeModuleId(options.scope)
  return [
    '/* eslint-disable */',
    '/* prettier-ignore */',
    '// oxfmt-ignore',
    '// Generated by `matrix prepare`. Do not edit manually.',
    'interface ImportMetaEnv {',
    ...keys.map(key => `  readonly ${key}${optional(key)}: string`),
    '}',
    '',
    `declare module '${moduleId}' {`,
    '  import type { MatrixRuntime } from \'@xova/matrix/runtime\'',
    '',
    '  interface MatrixConfig {',
    ...configNames.map(name => `    readonly ${name}${optional(fields.get(name)!)}: ${configType(fields.get(name)!)}`),
    '  }',
    '',
    '  export const matrix: MatrixRuntime<MatrixConfig>',
    '}',
    '',
  ].join('\n')
}

/** Generates project-local declarations without writing any environment values. */
export async function generateMatrixTypes(options: GenerateMatrixTypesOptions): Promise<string> {
  const output = matrixTypeOutput(options)
  const declarations = renderMatrixTypes(options)
  await mkdir(path.dirname(output), { recursive: true })
  const existing = await readFile(output, 'utf8').catch(() => undefined)
  if (existing !== declarations) {
    const temporary = `${output}.${randomUUID()}.tmp`
    await writeFile(temporary, declarations)
    await rename(temporary, output)
  }
  return output
}

export function matrixTypeEnvKeys(...envs: Array<Record<string, unknown> | undefined>): Record<string, string> {
  return Object.fromEntries([...new Set(envs.flatMap(env => env ? Object.keys(env) : []))].map(key => [key, '']))
}
