import type { EnvPrefix } from './env.js'
import { randomUUID } from 'node:crypto'
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { ensureMatrixEnvPrefix, publicEnvConfigName, publicEnvKeys } from './env.js'

export interface GenerateMatrixTypesOptions {
  cwd: string
  env: Record<string, unknown>
  envPrefix?: EnvPrefix
  scope?: string
  output?: string
}

export function matrixRuntimeModuleId(scope?: string): string {
  if (!scope)
    return 'virtual:matrix/runtime'
  if (!/^[\w-]+$/.test(scope))
    throw new Error(`Invalid Matrix scope: ${scope}`)
  return `virtual:matrix/runtime/${scope}`
}

/** Generates project-local declarations without writing any environment values. */
export async function generateMatrixTypes(options: GenerateMatrixTypesOptions): Promise<string> {
  const prefixes = ensureMatrixEnvPrefix(options.envPrefix)
  const keys = publicEnvKeys(options.env, prefixes)
  const configNames = keys
    .map(key => publicEnvConfigName(key, prefixes))
    .filter(Boolean)
  const uniqueConfigNames = [...new Set(configNames)].sort()
  const moduleId = matrixRuntimeModuleId(options.scope)
  const defaultOutput = options.scope
    ? `.matrix/types/matrix-runtime-${options.scope}.d.ts`
    : '.matrix/types/matrix-runtime.d.ts'
  const output = path.resolve(options.cwd, options.output ?? defaultOutput)
  const declarations = [
    '// Generated by `matrix prepare`. Do not edit manually.',
    'import type { MatrixRuntime } from \'@xova/matrix/runtime\'',
    '',
    'interface MatrixConfig {',
    ...uniqueConfigNames.map(name => `  readonly ${name}: string`),
    '}',
    '',
    'declare global {',
    '  interface ImportMetaEnv {',
    ...keys.map(key => `    readonly ${key}: string`),
    '  }',
    '}',
    '',
    `declare module '${moduleId}' {`,
    '  const matrix: MatrixRuntime<MatrixConfig>',
    '  export { matrix }',
    '}',
    '',
  ].join('\n')
  await mkdir(path.dirname(output), { recursive: true })
  const existing = await readFile(output, 'utf8').catch(() => undefined)
  if (existing !== declarations) {
    const temporary = `${output}.${randomUUID()}.tmp`
    await writeFile(temporary, declarations)
    await rename(temporary, output)
  }
  return output
}

export function matrixTypeEnvKeys(...envs: Array<Record<string, unknown> | undefined>): Record<string, string> {
  return Object.fromEntries([...new Set(envs.flatMap(env => env ? Object.keys(env) : []))].map(key => [key, '']))
}
