name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    uses: xova-dev/.github/.github/workflows/npm-publish.yml@main
    with:
      verify-command: pnpm check && pnpm test:pack
      publish-command: pnpm publish --access public
